-   id: alejandra
    name: alejandra
    description: 'Format Nix code with Alejandra'
    entry: alejandra
    language: rust
    'files': \.nix$
    args: []
    require_serial: false
    additional_dependencies: ["cli:alejandra:1.5.0"]
    minimum_pre_commit_version: '0'
